#!/bin/bash

# Portable Node.js
# 2016/03/24 by thinkbase.net@gmail.com

if [ -z $BASH ]; then
    echo "This shell script MUST run under bash."
    exit -1
fi
_script="$(readlink -f "${BASH_SOURCE[0]}")"
_script_dir="$(dirname "$_script")"
# echo "Directory of $_script : $_script_dir"

set -o nounset
set -o errexit

source "${_script_dir}/inst/node-install"

"${NODE_RUNTIME_DIR}/bin/node" $@

